FROM node:20-alpine

WORKDIR /app

# Build-time vars for Vite (Render passes service env vars marked "Available at build time" as build args)
ARG VITE_SUPERTOKENS_AUTH_ENABLED
ARG VITE_SUPERTOKENS_APP_NAME
ARG VITE_SUPERTOKENS_API_DOMAIN
ARG VITE_SUPERTOKENS_WEBSITE_DOMAIN
ARG VITE_SUPERTOKENS_API_BASE_PATH
ARG VITE_SUPERTOKENS_WEBSITE_BASE_PATH
ARG VITE_SUPPORT_HREF

ENV VITE_SUPERTOKENS_AUTH_ENABLED=$VITE_SUPERTOKENS_AUTH_ENABLED \
    VITE_SUPERTOKENS_APP_NAME=$VITE_SUPERTOKENS_APP_NAME \
    VITE_SUPERTOKENS_API_DOMAIN=$VITE_SUPERTOKENS_API_DOMAIN \
    VITE_SUPERTOKENS_WEBSITE_DOMAIN=$VITE_SUPERTOKENS_WEBSITE_DOMAIN \
    VITE_SUPERTOKENS_API_BASE_PATH=$VITE_SUPERTOKENS_API_BASE_PATH \
    VITE_SUPERTOKENS_WEBSITE_BASE_PATH=$VITE_SUPERTOKENS_WEBSITE_BASE_PATH \
    VITE_SUPPORT_HREF=$VITE_SUPPORT_HREF

# Backend deps
COPY backend/package*.json backend/
RUN cd backend && npm ci --omit=dev

# Frontend deps + build
COPY frontend/package*.json frontend/
RUN cd frontend && npm ci
COPY frontend/ frontend/
RUN cd frontend && npm run build

# Backend source + build
COPY backend/ backend/
RUN cd backend && npm run build

ENV NODE_ENV=production PORT=8080
EXPOSE 8080
CMD ["node", "backend/dist/server.js"]
